trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '6.x'

steps: 
- script: dotnet build --configuration ($buildConfiguration)
  displayName: 'dotnet build ($buildConfiguration)'
